environment:
  language: ruby

  language_versions:
  - 2.0.0_p451_p1
  - 2.1.2
  - jruby-1.7.9 # used by data-service and data-processor
  - jruby-1.7.11 # used by ubergateway
  - jruby-1.7.12
  - 2.2.3_p173_openssl_1.0.2d

notifications:
  - hipchat: 353885

build:
  run:
  - bundle install
  - bundle exec rake
